# run: conda env create --file dpn-gpu-environment.yml
name: dpn-gpu-env
channels:
- defaults
- conda-forge
dependencies:
- pandas
- numpy
- dill
- scipy
- pillow
- cython
- matplotlib
- scikit-image
- h5py
- ipython
- jupyter
- jupyterlab
- tensorflow-gpu
- keras=2.2.5
- imgaug
- opencv
- seaborn
- ipywidgets
- wget
